export const GAME_ACTIONS = {
  GAME_PLAYER_MOVED: 'GAME_PLAYER_MOVED',
  GAME_HISTORY_CHANGED: 'GAME_HISTORY_CHANGED',
  LOAD_GAME_INFO: 'LOAD_GAME_INFO'
};

export const LOGIN_ACTIONS = {
  LOAD_APP: 'LOAD_APP',
  APP_LOADED: 'APP_LOADED',
  LOGIN_LOADING: 'LOGIN_LOADING',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT'
};

export const USER_ACTIONS = {
  SET_USER_INFO: 'SET_USER_INFO'
};
